### ISSUE TITLE
Running the reagi game off from repo

### ISSUE THREAD

**Issue by danielsz** [leonardoborges/ClojureReactiveProgramming#2]
I'm trying to run the game off from the repo. 

I've ran `lein repl`and `(run)`, I go to `localhost:3000`, but nothing shows up and the console says 

``` js
Uncaught TypeError: undefined is not a function
```

Offending line in reagi_game.js:

``` js
 cljs.core.PersistentQueue.EMPTY = new cljs.core.PersistentQueue(null, 0, null, cljs.core.with_meta(cljs.core.PersistentVector.EMPTY, new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null, "file", "file", 1017047278), 
```

I must be doing something wrong.

**Comment by theleoborges** [comment]
I just cloned the repo again to make sure I didn't have a snowflake in my local machine. Steps performed:
1. `git clone git@github.com:leonardoborges/ClojureReactiveProgramming.git`
2. `cd ClojureReactiveProgramming/code/chapter06/`
3. `lein repl`
4. `user => (run)`
5. browsed to `http://localhost:3000/`

These steps worked for me. I'm using Leiningen `2.5.0`. All other deps should be pulled from project.clj.

Do you have anything in your lein user profiles that could be causing a conflict?

**Comment by danielsz** [comment]
You're asking the right questions! I've deleted my profiles to work with a clean slate, and the app started working as it should. Leiningen can be tricky. Thanks!

To be perfectly pedantic, I think step 2 should be: 

``` bash
cd ClojureReactiveProgramming/code/chapter06/reagi-game/
```

**Comment by theleoborges** [comment]
You're absolutely correct about step 2 :)

I'm glad things started working for you - leiningen profiles have bitten me before :)

**Comment by danielsz** [comment]
Thanks again. FYI, here's a bootified version of your game: 

https://github.com/danielsz/asteroids-frp

After cloning, type in the command line: 

``` bash
boot serve watch speak reload cljs
```

IMHO, a superior experience!

**Comment by theleoborges** [comment]
Thanks for that! It'll be a great reference for people coming to this repo!

If you happen to bootify more, let me know, I'll more than happily list them in the readme.

**Comment by danielsz** [comment]
Will do. :-)
